// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/models/room.proto

package hotelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,4,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Status        RoomStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=hotel.v1.RoomStatus" json:"status,omitempty"`
	Type          RoomType               `protobuf:"varint,6,opt,name=type,proto3,enum=hotel.v1.RoomType" json:"type,omitempty"`
	Price         string                 `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Capacity      int64                  `protobuf:"varint,8,opt,name=capacity,proto3" json:"capacity,omitempty"`
	AreaSqm       float32                `protobuf:"fixed32,9,opt,name=area_sqm,json=areaSqm,proto3" json:"area_sqm,omitempty"`
	Floor         int64                  `protobuf:"varint,10,opt,name=floor,proto3" json:"floor,omitempty"`
	Amenities     []string               `protobuf:"bytes,11,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Images        []string               `protobuf:"bytes,12,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoom) Reset() {
	*x = CreateRoom{}
	mi := &file_hotel_v1_models_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoom) ProtoMessage() {}

func (x *CreateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_models_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoom.ProtoReflect.Descriptor instead.
func (*CreateRoom) Descriptor() ([]byte, []int) {
	return file_hotel_v1_models_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateRoom) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRoom) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateRoom) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *CreateRoom) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *CreateRoom) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *CreateRoom) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CreateRoom) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateRoom) GetAreaSqm() float32 {
	if x != nil {
		return x.AreaSqm
	}
	return 0
}

func (x *CreateRoom) GetFloor() int64 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *CreateRoom) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *CreateRoom) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateRoom) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreateRoom) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_hotel_v1_models_room_proto protoreflect.FileDescriptor

const file_hotel_v1_models_room_proto_rawDesc = "" +
	"\n" +
	"\x1ahotel/v1/models/room.proto\x12\bhotel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a hotel/v1/enums/room_status.proto\x1a\x1ehotel/v1/enums/room_type.proto\"\xef\x03\n" +
	"\n" +
	"CreateRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\vroom_number\x18\x04 \x01(\tR\n" +
	"roomNumber\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.hotel.v1.RoomStatusR\x06status\x12&\n" +
	"\x04type\x18\x06 \x01(\x0e2\x12.hotel.v1.RoomTypeR\x04type\x12\x14\n" +
	"\x05price\x18\a \x01(\tR\x05price\x12\x1a\n" +
	"\bcapacity\x18\b \x01(\x03R\bcapacity\x12\x19\n" +
	"\barea_sqm\x18\t \x01(\x02R\aareaSqm\x12\x14\n" +
	"\x05floor\x18\n" +
	" \x01(\x03R\x05floor\x12\x1c\n" +
	"\tamenities\x18\v \x03(\tR\tamenities\x12\x16\n" +
	"\x06images\x18\f \x03(\tR\x06images\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_models_room_proto_rawDescOnce sync.Once
	file_hotel_v1_models_room_proto_rawDescData []byte
)

func file_hotel_v1_models_room_proto_rawDescGZIP() []byte {
	file_hotel_v1_models_room_proto_rawDescOnce.Do(func() {
		file_hotel_v1_models_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_models_room_proto_rawDesc), len(file_hotel_v1_models_room_proto_rawDesc)))
	})
	return file_hotel_v1_models_room_proto_rawDescData
}

var file_hotel_v1_models_room_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hotel_v1_models_room_proto_goTypes = []any{
	(*CreateRoom)(nil),            // 0: hotel.v1.CreateRoom
	(RoomStatus)(0),               // 1: hotel.v1.RoomStatus
	(RoomType)(0),                 // 2: hotel.v1.RoomType
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_hotel_v1_models_room_proto_depIdxs = []int32{
	1, // 0: hotel.v1.CreateRoom.status:type_name -> hotel.v1.RoomStatus
	2, // 1: hotel.v1.CreateRoom.type:type_name -> hotel.v1.RoomType
	3, // 2: hotel.v1.CreateRoom.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: hotel.v1.CreateRoom.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hotel_v1_models_room_proto_init() }
func file_hotel_v1_models_room_proto_init() {
	if File_hotel_v1_models_room_proto != nil {
		return
	}
	file_hotel_v1_enums_room_status_proto_init()
	file_hotel_v1_enums_room_type_proto_init()
	file_hotel_v1_models_room_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_models_room_proto_rawDesc), len(file_hotel_v1_models_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_models_room_proto_goTypes,
		DependencyIndexes: file_hotel_v1_models_room_proto_depIdxs,
		MessageInfos:      file_hotel_v1_models_room_proto_msgTypes,
	}.Build()
	File_hotel_v1_models_room_proto = out.File
	file_hotel_v1_models_room_proto_goTypes = nil
	file_hotel_v1_models_room_proto_depIdxs = nil
}
