// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/booking_messages.proto

package bookingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingStatus int32

const (
	BookingStatus_BOOKING_STATUS_UNSPECIFIED BookingStatus = 0
	BookingStatus_BOOKING_STATUS_PENDING     BookingStatus = 1
	BookingStatus_BOOKING_STATUS_CONFIRMED   BookingStatus = 2
	BookingStatus_BOOKING_STATUS_CANCELLED   BookingStatus = 3
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_PENDING",
		2: "BOOKING_STATUS_CONFIRMED",
		3: "BOOKING_STATUS_CANCELLED",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_PENDING":     1,
		"BOOKING_STATUS_CONFIRMED":   2,
		"BOOKING_STATUS_CANCELLED":   3,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_messages_proto_enumTypes[0].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_messages_proto_enumTypes[0]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_messages_proto_rawDescGZIP(), []int{0}
}

type Booking struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HotelId          string                 `protobuf:"bytes,3,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	BookingRooms     []*BookingRoomResponse `protobuf:"bytes,4,rep,name=booking_rooms,json=bookingRooms,proto3" json:"booking_rooms,omitempty"`
	CheckIn          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckOut         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	Status           BookingStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=booking.v1.BookingStatus" json:"status,omitempty"`
	GuestName        string                 `protobuf:"bytes,8,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	GuestEmail       *string                `protobuf:"bytes,9,opt,name=guest_email,json=guestEmail,proto3,oneof" json:"guest_email,omitempty"`
	GuestPhone       *string                `protobuf:"bytes,10,opt,name=guest_phone,json=guestPhone,proto3,oneof" json:"guest_phone,omitempty"`
	Currency         string                 `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	FinalTotalAmount string                 `protobuf:"bytes,12,opt,name=final_total_amount,json=finalTotalAmount,proto3" json:"final_total_amount,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_booking_v1_booking_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Booking) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *Booking) GetBookingRooms() []*BookingRoomResponse {
	if x != nil {
		return x.BookingRooms
	}
	return nil
}

func (x *Booking) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *Booking) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

func (x *Booking) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *Booking) GetGuestName() string {
	if x != nil {
		return x.GuestName
	}
	return ""
}

func (x *Booking) GetGuestEmail() string {
	if x != nil && x.GuestEmail != nil {
		return *x.GuestEmail
	}
	return ""
}

func (x *Booking) GetGuestPhone() string {
	if x != nil && x.GuestPhone != nil {
		return *x.GuestPhone
	}
	return ""
}

func (x *Booking) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Booking) GetFinalTotalAmount() string {
	if x != nil {
		return x.FinalTotalAmount
	}
	return ""
}

func (x *Booking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Booking) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BookingShort struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId              int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HotelId             string                 `protobuf:"bytes,3,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	CheckIn             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckOut            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	Status              BookingStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=booking.v1.BookingStatus" json:"status,omitempty"`
	GuestName           string                 `protobuf:"bytes,7,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	GuestEmail          *string                `protobuf:"bytes,8,opt,name=guest_email,json=guestEmail,proto3,oneof" json:"guest_email,omitempty"`
	GuestPhone          *string                `protobuf:"bytes,9,opt,name=guest_phone,json=guestPhone,proto3,oneof" json:"guest_phone,omitempty"`
	Currency            string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	ExpectedTotalAmount string                 `protobuf:"bytes,11,opt,name=expected_total_amount,json=expectedTotalAmount,proto3" json:"expected_total_amount,omitempty"`
	FinalTotalAmount    string                 `protobuf:"bytes,12,opt,name=final_total_amount,json=finalTotalAmount,proto3" json:"final_total_amount,omitempty"`
	Rooms               []*BookingRoomShort    `protobuf:"bytes,13,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BookingShort) Reset() {
	*x = BookingShort{}
	mi := &file_booking_v1_booking_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingShort) ProtoMessage() {}

func (x *BookingShort) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingShort.ProtoReflect.Descriptor instead.
func (*BookingShort) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_messages_proto_rawDescGZIP(), []int{1}
}

func (x *BookingShort) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingShort) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BookingShort) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *BookingShort) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *BookingShort) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

func (x *BookingShort) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *BookingShort) GetGuestName() string {
	if x != nil {
		return x.GuestName
	}
	return ""
}

func (x *BookingShort) GetGuestEmail() string {
	if x != nil && x.GuestEmail != nil {
		return *x.GuestEmail
	}
	return ""
}

func (x *BookingShort) GetGuestPhone() string {
	if x != nil && x.GuestPhone != nil {
		return *x.GuestPhone
	}
	return ""
}

func (x *BookingShort) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BookingShort) GetExpectedTotalAmount() string {
	if x != nil {
		return x.ExpectedTotalAmount
	}
	return ""
}

func (x *BookingShort) GetFinalTotalAmount() string {
	if x != nil {
		return x.FinalTotalAmount
	}
	return ""
}

func (x *BookingShort) GetRooms() []*BookingRoomShort {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type BookingRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Adults        uint32                 `protobuf:"varint,3,opt,name=adults,proto3" json:"adults,omitempty"`
	Children      uint32                 `protobuf:"varint,4,opt,name=children,proto3" json:"children,omitempty"`
	PricePerNight string                 `protobuf:"bytes,5,opt,name=price_per_night,json=pricePerNight,proto3" json:"price_per_night,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingRoomResponse) Reset() {
	*x = BookingRoomResponse{}
	mi := &file_booking_v1_booking_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRoomResponse) ProtoMessage() {}

func (x *BookingRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRoomResponse.ProtoReflect.Descriptor instead.
func (*BookingRoomResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_messages_proto_rawDescGZIP(), []int{2}
}

func (x *BookingRoomResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BookingRoomResponse) GetAdults() uint32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *BookingRoomResponse) GetChildren() uint32 {
	if x != nil {
		return x.Children
	}
	return 0
}

func (x *BookingRoomResponse) GetPricePerNight() string {
	if x != nil {
		return x.PricePerNight
	}
	return ""
}

type BookingRoomShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Adults        uint32                 `protobuf:"varint,3,opt,name=adults,proto3" json:"adults,omitempty"`
	Children      uint32                 `protobuf:"varint,4,opt,name=children,proto3" json:"children,omitempty"`
	PricePerNight string                 `protobuf:"bytes,5,opt,name=price_per_night,json=pricePerNight,proto3" json:"price_per_night,omitempty"`
	RoomLock      *RoomLockShort         `protobuf:"bytes,6,opt,name=room_lock,json=roomLock,proto3,oneof" json:"room_lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingRoomShort) Reset() {
	*x = BookingRoomShort{}
	mi := &file_booking_v1_booking_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRoomShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRoomShort) ProtoMessage() {}

func (x *BookingRoomShort) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRoomShort.ProtoReflect.Descriptor instead.
func (*BookingRoomShort) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_messages_proto_rawDescGZIP(), []int{3}
}

func (x *BookingRoomShort) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingRoomShort) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BookingRoomShort) GetAdults() uint32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *BookingRoomShort) GetChildren() uint32 {
	if x != nil {
		return x.Children
	}
	return 0
}

func (x *BookingRoomShort) GetPricePerNight() string {
	if x != nil {
		return x.PricePerNight
	}
	return ""
}

func (x *BookingRoomShort) GetRoomLock() *RoomLockShort {
	if x != nil {
		return x.RoomLock
	}
	return nil
}

type RoomLockShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StayRange     *DateRange             `protobuf:"bytes,2,opt,name=stay_range,json=stayRange,proto3" json:"stay_range,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLockShort) Reset() {
	*x = RoomLockShort{}
	mi := &file_booking_v1_booking_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLockShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLockShort) ProtoMessage() {}

func (x *RoomLockShort) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLockShort.ProtoReflect.Descriptor instead.
func (*RoomLockShort) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RoomLockShort) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomLockShort) GetStayRange() *DateRange {
	if x != nil {
		return x.StayRange
	}
	return nil
}

func (x *RoomLockShort) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *RoomLockShort) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RoomLockShort) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_booking_v1_booking_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_messages_proto_rawDescGZIP(), []int{5}
}

func (x *DateRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *DateRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

var File_booking_v1_booking_messages_proto protoreflect.FileDescriptor

const file_booking_v1_booking_messages_proto_rawDesc = "" +
	"\n" +
	"!booking/v1/booking_messages.proto\x12\n" +
	"booking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x05\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\bhotel_id\x18\x03 \x01(\tR\ahotelId\x12D\n" +
	"\rbooking_rooms\x18\x04 \x03(\v2\x1f.booking.v1.BookingRoomResponseR\fbookingRooms\x125\n" +
	"\bcheck_in\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\acheckIn\x127\n" +
	"\tcheck_out\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bcheckOut\x121\n" +
	"\x06status\x18\a \x01(\x0e2\x19.booking.v1.BookingStatusR\x06status\x12\x1d\n" +
	"\n" +
	"guest_name\x18\b \x01(\tR\tguestName\x12$\n" +
	"\vguest_email\x18\t \x01(\tH\x00R\n" +
	"guestEmail\x88\x01\x01\x12$\n" +
	"\vguest_phone\x18\n" +
	" \x01(\tH\x01R\n" +
	"guestPhone\x88\x01\x01\x12\x1a\n" +
	"\bcurrency\x18\v \x01(\tR\bcurrency\x12,\n" +
	"\x12final_total_amount\x18\f \x01(\tR\x10finalTotalAmount\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_guest_emailB\x0e\n" +
	"\f_guest_phone\"\xb2\x04\n" +
	"\fBookingShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\bhotel_id\x18\x03 \x01(\tR\ahotelId\x125\n" +
	"\bcheck_in\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acheckIn\x127\n" +
	"\tcheck_out\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bcheckOut\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.booking.v1.BookingStatusR\x06status\x12\x1d\n" +
	"\n" +
	"guest_name\x18\a \x01(\tR\tguestName\x12$\n" +
	"\vguest_email\x18\b \x01(\tH\x00R\n" +
	"guestEmail\x88\x01\x01\x12$\n" +
	"\vguest_phone\x18\t \x01(\tH\x01R\n" +
	"guestPhone\x88\x01\x01\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\x122\n" +
	"\x15expected_total_amount\x18\v \x01(\tR\x13expectedTotalAmount\x12,\n" +
	"\x12final_total_amount\x18\f \x01(\tR\x10finalTotalAmount\x122\n" +
	"\x05rooms\x18\r \x03(\v2\x1c.booking.v1.BookingRoomShortR\x05roomsB\x0e\n" +
	"\f_guest_emailB\x0e\n" +
	"\f_guest_phone\"\x9a\x01\n" +
	"\x13BookingRoomResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06adults\x18\x03 \x01(\rR\x06adults\x12\x1a\n" +
	"\bchildren\x18\x04 \x01(\rR\bchildren\x12&\n" +
	"\x0fprice_per_night\x18\x05 \x01(\tR\rpricePerNight\"\xe2\x01\n" +
	"\x10BookingRoomShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06adults\x18\x03 \x01(\rR\x06adults\x12\x1a\n" +
	"\bchildren\x18\x04 \x01(\rR\bchildren\x12&\n" +
	"\x0fprice_per_night\x18\x05 \x01(\tR\rpricePerNight\x12;\n" +
	"\troom_lock\x18\x06 \x01(\v2\x19.booking.v1.RoomLockShortH\x00R\broomLock\x88\x01\x01B\f\n" +
	"\n" +
	"_room_lock\"\xfc\x01\n" +
	"\rRoomLockShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\n" +
	"stay_range\x18\x02 \x01(\v2\x15.booking.v1.DateRangeR\tstayRange\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12>\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\r\n" +
	"\v_expires_at\"k\n" +
	"\tDateRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end*\x87\x01\n" +
	"\rBookingStatus\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BOOKING_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18BOOKING_STATUS_CONFIRMED\x10\x02\x12\x1c\n" +
	"\x18BOOKING_STATUS_CANCELLED\x10\x03B\"Z booking/api/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_booking_messages_proto_rawDescOnce sync.Once
	file_booking_v1_booking_messages_proto_rawDescData []byte
)

func file_booking_v1_booking_messages_proto_rawDescGZIP() []byte {
	file_booking_v1_booking_messages_proto_rawDescOnce.Do(func() {
		file_booking_v1_booking_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_booking_messages_proto_rawDesc), len(file_booking_v1_booking_messages_proto_rawDesc)))
	})
	return file_booking_v1_booking_messages_proto_rawDescData
}

var file_booking_v1_booking_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_booking_v1_booking_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_booking_v1_booking_messages_proto_goTypes = []any{
	(BookingStatus)(0),            // 0: booking.v1.BookingStatus
	(*Booking)(nil),               // 1: booking.v1.Booking
	(*BookingShort)(nil),          // 2: booking.v1.BookingShort
	(*BookingRoomResponse)(nil),   // 3: booking.v1.BookingRoomResponse
	(*BookingRoomShort)(nil),      // 4: booking.v1.BookingRoomShort
	(*RoomLockShort)(nil),         // 5: booking.v1.RoomLockShort
	(*DateRange)(nil),             // 6: booking.v1.DateRange
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_booking_v1_booking_messages_proto_depIdxs = []int32{
	3,  // 0: booking.v1.Booking.booking_rooms:type_name -> booking.v1.BookingRoomResponse
	7,  // 1: booking.v1.Booking.check_in:type_name -> google.protobuf.Timestamp
	7,  // 2: booking.v1.Booking.check_out:type_name -> google.protobuf.Timestamp
	0,  // 3: booking.v1.Booking.status:type_name -> booking.v1.BookingStatus
	7,  // 4: booking.v1.Booking.created_at:type_name -> google.protobuf.Timestamp
	7,  // 5: booking.v1.Booking.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 6: booking.v1.BookingShort.check_in:type_name -> google.protobuf.Timestamp
	7,  // 7: booking.v1.BookingShort.check_out:type_name -> google.protobuf.Timestamp
	0,  // 8: booking.v1.BookingShort.status:type_name -> booking.v1.BookingStatus
	4,  // 9: booking.v1.BookingShort.rooms:type_name -> booking.v1.BookingRoomShort
	5,  // 10: booking.v1.BookingRoomShort.room_lock:type_name -> booking.v1.RoomLockShort
	6,  // 11: booking.v1.RoomLockShort.stay_range:type_name -> booking.v1.DateRange
	7,  // 12: booking.v1.RoomLockShort.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 13: booking.v1.RoomLockShort.created_at:type_name -> google.protobuf.Timestamp
	7,  // 14: booking.v1.DateRange.start:type_name -> google.protobuf.Timestamp
	7,  // 15: booking.v1.DateRange.end:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_messages_proto_init() }
func file_booking_v1_booking_messages_proto_init() {
	if File_booking_v1_booking_messages_proto != nil {
		return
	}
	file_booking_v1_booking_messages_proto_msgTypes[0].OneofWrappers = []any{}
	file_booking_v1_booking_messages_proto_msgTypes[1].OneofWrappers = []any{}
	file_booking_v1_booking_messages_proto_msgTypes[3].OneofWrappers = []any{}
	file_booking_v1_booking_messages_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_messages_proto_rawDesc), len(file_booking_v1_booking_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_booking_messages_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_messages_proto_depIdxs,
		EnumInfos:         file_booking_v1_booking_messages_proto_enumTypes,
		MessageInfos:      file_booking_v1_booking_messages_proto_msgTypes,
	}.Build()
	File_booking_v1_booking_messages_proto = out.File
	file_booking_v1_booking_messages_proto_goTypes = nil
	file_booking_v1_booking_messages_proto_depIdxs = nil
}
