// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/models/common.proto

package bookingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_booking_v1_models_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_models_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_booking_v1_models_common_proto_rawDescGZIP(), []int{0}
}

func (x *DateRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *DateRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

var File_booking_v1_models_common_proto protoreflect.FileDescriptor

const file_booking_v1_models_common_proto_rawDesc = "" +
	"\n" +
	"\x1ebooking/v1/models/common.proto\x12\n" +
	"booking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\tDateRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03endB\x1aZ\x18api/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_models_common_proto_rawDescOnce sync.Once
	file_booking_v1_models_common_proto_rawDescData []byte
)

func file_booking_v1_models_common_proto_rawDescGZIP() []byte {
	file_booking_v1_models_common_proto_rawDescOnce.Do(func() {
		file_booking_v1_models_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_models_common_proto_rawDesc), len(file_booking_v1_models_common_proto_rawDesc)))
	})
	return file_booking_v1_models_common_proto_rawDescData
}

var file_booking_v1_models_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_booking_v1_models_common_proto_goTypes = []any{
	(*DateRange)(nil),             // 0: booking.v1.DateRange
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_booking_v1_models_common_proto_depIdxs = []int32{
	1, // 0: booking.v1.DateRange.start:type_name -> google.protobuf.Timestamp
	1, // 1: booking.v1.DateRange.end:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_booking_v1_models_common_proto_init() }
func file_booking_v1_models_common_proto_init() {
	if File_booking_v1_models_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_models_common_proto_rawDesc), len(file_booking_v1_models_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_models_common_proto_goTypes,
		DependencyIndexes: file_booking_v1_models_common_proto_depIdxs,
		MessageInfos:      file_booking_v1_models_common_proto_msgTypes,
	}.Build()
	File_booking_v1_models_common_proto = out.File
	file_booking_v1_models_common_proto_goTypes = nil
	file_booking_v1_models_common_proto_depIdxs = nil
}
