// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/rpc/get_booking_room.proto

package bookingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookingRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRoomRequest) Reset() {
	*x = GetBookingRoomRequest{}
	mi := &file_booking_v1_rpc_get_booking_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRoomRequest) ProtoMessage() {}

func (x *GetBookingRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_get_booking_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRoomRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRoomRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_get_booking_room_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookingRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBookingRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingRoom   *BookingRoomFullInfo   `protobuf:"bytes,1,opt,name=booking_room,json=bookingRoom,proto3" json:"booking_room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRoomResponse) Reset() {
	*x = GetBookingRoomResponse{}
	mi := &file_booking_v1_rpc_get_booking_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRoomResponse) ProtoMessage() {}

func (x *GetBookingRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_get_booking_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRoomResponse.ProtoReflect.Descriptor instead.
func (*GetBookingRoomResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_get_booking_room_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookingRoomResponse) GetBookingRoom() *BookingRoomFullInfo {
	if x != nil {
		return x.BookingRoom
	}
	return nil
}

var File_booking_v1_rpc_get_booking_room_proto protoreflect.FileDescriptor

const file_booking_v1_rpc_get_booking_room_proto_rawDesc = "" +
	"\n" +
	"%booking/v1/rpc/get_booking_room.proto\x12\n" +
	"booking.v1\x1a\x1bbuf/validate/validate.proto\x1a$booking/v1/models/booking_room.proto\"1\n" +
	"\x15GetBookingRoomRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\\\n" +
	"\x16GetBookingRoomResponse\x12B\n" +
	"\fbooking_room\x18\x01 \x01(\v2\x1f.booking.v1.BookingRoomFullInfoR\vbookingRoomB\x1aZ\x18api/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_rpc_get_booking_room_proto_rawDescOnce sync.Once
	file_booking_v1_rpc_get_booking_room_proto_rawDescData []byte
)

func file_booking_v1_rpc_get_booking_room_proto_rawDescGZIP() []byte {
	file_booking_v1_rpc_get_booking_room_proto_rawDescOnce.Do(func() {
		file_booking_v1_rpc_get_booking_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_get_booking_room_proto_rawDesc), len(file_booking_v1_rpc_get_booking_room_proto_rawDesc)))
	})
	return file_booking_v1_rpc_get_booking_room_proto_rawDescData
}

var file_booking_v1_rpc_get_booking_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booking_v1_rpc_get_booking_room_proto_goTypes = []any{
	(*GetBookingRoomRequest)(nil),  // 0: booking.v1.GetBookingRoomRequest
	(*GetBookingRoomResponse)(nil), // 1: booking.v1.GetBookingRoomResponse
	(*BookingRoomFullInfo)(nil),    // 2: booking.v1.BookingRoomFullInfo
}
var file_booking_v1_rpc_get_booking_room_proto_depIdxs = []int32{
	2, // 0: booking.v1.GetBookingRoomResponse.booking_room:type_name -> booking.v1.BookingRoomFullInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_booking_v1_rpc_get_booking_room_proto_init() }
func file_booking_v1_rpc_get_booking_room_proto_init() {
	if File_booking_v1_rpc_get_booking_room_proto != nil {
		return
	}
	file_booking_v1_models_booking_room_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_get_booking_room_proto_rawDesc), len(file_booking_v1_rpc_get_booking_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_rpc_get_booking_room_proto_goTypes,
		DependencyIndexes: file_booking_v1_rpc_get_booking_room_proto_depIdxs,
		MessageInfos:      file_booking_v1_rpc_get_booking_room_proto_msgTypes,
	}.Build()
	File_booking_v1_rpc_get_booking_room_proto = out.File
	file_booking_v1_rpc_get_booking_room_proto_goTypes = nil
	file_booking_v1_rpc_get_booking_room_proto_depIdxs = nil
}
