// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/models/room_lock.proto

package bookingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomLockShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StayRange     *DateRange             `protobuf:"bytes,2,opt,name=stay_range,json=stayRange,proto3" json:"stay_range,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLockShort) Reset() {
	*x = RoomLockShort{}
	mi := &file_booking_v1_models_room_lock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLockShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLockShort) ProtoMessage() {}

func (x *RoomLockShort) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_models_room_lock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLockShort.ProtoReflect.Descriptor instead.
func (*RoomLockShort) Descriptor() ([]byte, []int) {
	return file_booking_v1_models_room_lock_proto_rawDescGZIP(), []int{0}
}

func (x *RoomLockShort) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomLockShort) GetStayRange() *DateRange {
	if x != nil {
		return x.StayRange
	}
	return nil
}

func (x *RoomLockShort) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *RoomLockShort) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RoomLockShort) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_booking_v1_models_room_lock_proto protoreflect.FileDescriptor

const file_booking_v1_models_room_lock_proto_rawDesc = "" +
	"\n" +
	"!booking/v1/models/room_lock.proto\x12\n" +
	"booking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ebooking/v1/models/common.proto\"\xfc\x01\n" +
	"\rRoomLockShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\n" +
	"stay_range\x18\x02 \x01(\v2\x15.booking.v1.DateRangeR\tstayRange\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12>\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\r\n" +
	"\v_expires_atB\x1aZ\x18api/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_models_room_lock_proto_rawDescOnce sync.Once
	file_booking_v1_models_room_lock_proto_rawDescData []byte
)

func file_booking_v1_models_room_lock_proto_rawDescGZIP() []byte {
	file_booking_v1_models_room_lock_proto_rawDescOnce.Do(func() {
		file_booking_v1_models_room_lock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_models_room_lock_proto_rawDesc), len(file_booking_v1_models_room_lock_proto_rawDesc)))
	})
	return file_booking_v1_models_room_lock_proto_rawDescData
}

var file_booking_v1_models_room_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_booking_v1_models_room_lock_proto_goTypes = []any{
	(*RoomLockShort)(nil),         // 0: booking.v1.RoomLockShort
	(*DateRange)(nil),             // 1: booking.v1.DateRange
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_booking_v1_models_room_lock_proto_depIdxs = []int32{
	1, // 0: booking.v1.RoomLockShort.stay_range:type_name -> booking.v1.DateRange
	2, // 1: booking.v1.RoomLockShort.expires_at:type_name -> google.protobuf.Timestamp
	2, // 2: booking.v1.RoomLockShort.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_booking_v1_models_room_lock_proto_init() }
func file_booking_v1_models_room_lock_proto_init() {
	if File_booking_v1_models_room_lock_proto != nil {
		return
	}
	file_booking_v1_models_common_proto_init()
	file_booking_v1_models_room_lock_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_models_room_lock_proto_rawDesc), len(file_booking_v1_models_room_lock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_models_room_lock_proto_goTypes,
		DependencyIndexes: file_booking_v1_models_room_lock_proto_depIdxs,
		MessageInfos:      file_booking_v1_models_room_lock_proto_msgTypes,
	}.Build()
	File_booking_v1_models_room_lock_proto = out.File
	file_booking_v1_models_room_lock_proto_goTypes = nil
	file_booking_v1_models_room_lock_proto_depIdxs = nil
}
